name: strict_lints
description: A linter rules set that enable as much linter options as possible.
version: 0.2.0
repository: https://github.com/treeinfra/strict_lints
environment: {sdk: ">=3.4.3 <4.0.0"}
topics: [analysis-options, code-style, lint, linter-options, strict]

dependencies:
  flutter_lints: ^4.0.0
